[package]
name = "cubespinner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9"
bevy_egui = "0.17"
rand = "0.8.5"
bevy_mod_picking = "0.10.0"
bevy_transform_gizmo = "0.4.0"